server {
    listen 80;
    server_name _;

    # Статика и медиа
    location /static/ {
        alias /static/;
    }

    location /media/ {
        alias /media/;
    }

    # Админка и API бэкенда
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
    }

    # Все остальные запросы – на фронтенд (React)
    location / {
        root /static;
        try_files $uri $uri/ /index.html;
    }
}